(env
 (dev
  (flags ())))

(library
 (public_name plugin1.plugin1_impl)
 (name plugin1_impl)
 (modules plugin1_impl)
 (library_flags (:standard))
 (flags
  (:standard
   ;-linkall
   ; explicit cclib doesn't help but...
   ;-cclib
   ;-lLLVM-16
   ;
   ))
 (ocamlopt_flags
  (:standard
   -linkall
   ;/media/work2/.opam/llvm16/lib/llvm/shared/llvm.cmxa
   ;
   ))
 (libraries
  app.register
  llvm
  ;unix
  ;LL
  ))

(plugin
 (name plugin1)
 (libraries plugin1.plugin1_impl llvm)
 (site
  (app plugins)))
